// This file is autogenerated by src/main/java/org/craftinginterpreters/tool/GenerateAst.java. Do not edit by hand!
package org.craftinginterpreters.lox;

abstract class Stmt {
    interface Visitor<R> {
        R visitExpressionStmt(final Expression stmt);
        R visitPrintStmt(final Print stmt);
    }

    static class Expression extends Stmt {
        Expression(final Expr expression) {
            this.expression = expression;
        }

        @Override
        <R> R accept(final Visitor<R> visitor) {
            return visitor.visitExpressionStmt(this);
        }

        final Expr expression;
    }

    static class Print extends Stmt {
        Print(final Expr expression) {
            this.expression = expression;
        }

        @Override
        <R> R accept(final Visitor<R> visitor) {
            return visitor.visitPrintStmt(this);
        }

        final Expr expression;
    }

    abstract <R> R accept(final Visitor<R> visitor);
}

